<div class="adsense" style="text-align: center;">
<!-- Google Adsense -->

<script type="text/javascript"><!--
google_ad_client = "ca-pub-0946473159682149";
/* 4walled wallpaper details */
google_ad_slot = "2283901613";
google_ad_width = 728;
google_ad_height = 90;
//-->
</script>
<script type="text/javascript"
src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script>

<!-- Google Adsense -->
</div>
<div id="ninja"></div>

<script type="text/javascript"><!--
	$(document).ready(function(){
		if (($(".adsense *").size() == $(".adsense").size()*2) || ($(".adsense *").size() == 0)){
			$("#ninja").prepend("<p style='text-align: center; width: 400px; margin: 0 auto 0 auto;'>Would be awesome if you could <strong>whitelist</strong> 4walled.cc in your adblock. We are using money from advertising to pay for the server, traffic etc...</p>");
		};
	});
//-->
</script>
